### ISSUE TITLE
Remove f-strings to allow installs from python<3.6

### ISSUE THREAD

**Issue by bthayer2365** [bthayer2365/git-gud#15]
As much as I love f-strings, I think we're going to have to remove them.

An f-string is a string that looks like this:
```
location = 'World'
f'Hello {location}!'
```
For Git Gud to work on versions of python < 3.6, we need to make it look like this
```
location = 'World'
'Hello {location}!'.format(location=location)
```

**Comment by Yenneferr** [comment]
hi @bthayer2365, may I take this issue?

**Comment by bthayer2365** [comment]
@Yenneferr I'm sorry, I've actually already solved this. I've been busy getting v0.1 out. (You can install it now using pip install gitgud now)

 If you'd like, look at the other issues I've got posted.

Also, look for TODOs in the code and see if there's something else you'd like to fix. Some easy issues might be any of the other ones tagged as `good first issue`, really anything except #5 would be relatively easy. Thanks for reaching out!

**Comment by sahansk2** [comment]
For anybody that sees this issue: we now require that Python>=3.6 so there should not be any need to accommodate Python installs from versions less than 3.6 by avoiding f-strings.

**Comment by sahansk2** [comment]
@benthayer ?

**Comment by benthayer** [comment]
Well, I guess this is perfect timing:

From [python.org](https://www.python.org/downloads/release/python-3510/):

> Python 3.5 will reach its "end of life" at the end of September 2020. 

Python 3.6 also has many other great features, so I'm happy to have the 3.6 requirement and to start using f-strings again. 

We originally put in the requirement because we started using pathlib, [which only works with `open` in Python 3.6](https://stackoverflow.com/questions/42694112/when-using-pathlib-getting-error-typeerror-invalid-file-posixpathexample-t)
